/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qZsZhPBVmo2
 */
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { CardHeader, CardContent, Card } from "@/components/ui/card";
import { useState } from "react";
import { cn } from "@/lib/utils";
import { ProfileSwitcher } from "./profile-switcher";
import { Footer } from "./footer";
import EquationEditor from "./science";
import { Button } from "./ui/button";
import IClientConfig from "@/interfaces/client/iclient-config";

export function Layout({ config }: { config: IClientConfig }) {
  const [currentPanel, setCurrentPanel] = useState("configuration");
  const configButtonStyle = (value: "configuration" | "simulation") => cn("text-gray-500 hover:text-white", value === currentPanel && "text-white");
  return (
    <div className="flex flex-col min-h-screen bg-gray-900">
      <header className="flex items-center justify-between p-6 bg-gray-800 shadow-md">
        <Link className="flex justify-between items-center space-x-2" href="#">
          <SpheresIcon className="w-6 h-6" />
          <span className="font-semibold text-lg">Spheres</span>
          <span className="font-semibold text-gray-400 text-lg">
            Personal Physics Simulator
          </span>
        </Link>
        <div className="flex">
        <ProfileSwitcher />
        <div className="flex items-center space-x-4 border-gray-400 px-1 rounded-lg ml-2">
          <Button onClick={() => setCurrentPanel("configuration")}>
            <p className={configButtonStyle("configuration")}>Configuration</p>
          </Button>
          <Button onClick={() => setCurrentPanel("simulation")}>
            <p className={configButtonStyle("simulation")}>Simulation</p>
          </Button>
        </div>
        </div>
      </header>
      {currentPanel === "configuration" && <ConfigurationPanel />}
      {currentPanel === "simulation" && <SimulationPanel />}
      <footer className="bg-gray-800 shadow-md">
        <Footer />
      </footer>
    </div>
  );
}

// coming soon simulation panel
const SimulationPanel = () => {
  return (
    <>
      <main className="flex-1 p-6">
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          <p>
            Coming soon...
          </p>
        </div>
      </main>
    </>
  )
}

const ConfigurationPanel = () => {
  return (
    <>
      <h1
        className="px-6 pt-6 pb-2 text-2xl font-semibold text-gray-300 bg-gray-900 shadow-md">
        Configuration Home
      </h1>
      <div className="flex">
            <p className="px-6 text-gray-400 justify-center flex items-center">
        Current Balance: &nbsp;<span className="font-semibold text-gray-300">$0.00</span>
        </p>
        <Button>
          <p>
            Manage Funds
          </p>
        </Button>
        </div>

      <main className="flex-1 p-6">
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-semibold">Astrophysics</h2>
                <Badge>12 to review</Badge>
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-gray-400">
                An overview of the basic launch and stellar target confirmation
                settings.
              </p>
              <EquationEditor />
            </CardContent>
            <div className="p-4">
              <Link
                className="inline-block text-blue-500 hover:underline"
                href="#"
              >
                Edit Configuration
              </Link>
            </div>
          </Card>
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-semibold">Materials</h2>
                <Badge>8 Options</Badge>
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-gray-400">
                Configure the stabilisation and material properties.
              </p>
            </CardContent>
            <Button>
            Manage Materials
            </Button>
            <Button>
            Edit Configuration
            </Button>
          </Card>
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-semibold">Thermodynamics</h2>
                <Badge>5 Options</Badge>
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-gray-400">
                Customize how to transform and manipulate energy.
              </p>
            </CardContent>
            <div className="p-4">
              <Link
                className="inline-block text-blue-400 hover:underline"
                href="#"
              >
                Edit Configuration
              </Link>
            </div>
          </Card>
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-semibold">Information</h2>
                <Badge>5 Options</Badge>
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-gray-400">
                Customize how to receive information.
              </p>
            </CardContent>
            <div className="p-4">
              <Link
                className="inline-block text-blue-400 hover:underline"
                href="#"
              >
                Edit Configuration
              </Link>
            </div>
          </Card>
        </div>
      </main>
    </>
  );
};

const SpheresIcon = (props: any) => {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" {...props}>
      <path d="M12 2a10 10 0 100 20 10 10 0 000-20zm0 18a8 8 0 110-16 8 8 0 010 16zm0-14a6 6 0 100 12 6 6 0 000-12zm0 10a4 4 0 110-8 4 4 0 010 8z" />
    </svg>
  );
};
